on:
  push:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  repository_dispatch: 
      types: [docs_updated]

jobs:
  mintlify_job:
    runs-on: ubuntu-latest
    name: Run mintlify job
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Run mintlify github action
        uses: mintlify/mintlify-multirepo-action@v0.9
        with:
          token: ${{ secrets.PUSH_TOKEN }}
          target-branch: docs
          force: true
          repos: |
            - owner: Nixtla
              repo: nixtla
              ref: docs
            - owner: Nixtla
              repo: statsforecast
              ref: docs
            - owner: Nixtla
              repo: mlforecast
              ref: docs
            - owner: Nixtla
              repo: neuralforecast
              ref: docs
            - owner: Nixtla
              repo: hierarchicalforecast
              ref: docs
            - owner: Nixtla
              repo: utilsforecast
              ref: docs
            - owner: Nixtla
              repo: datasetsforecast
              ref: docs
            - owner: Nixtla
              repo: coreforecast
              ref: docs
