name: Test jq

on: workflow_dispatch

jobs:
  test-jq:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test jq
        run: |
          jq -s '{
            config: .[0],
            navigations: [
              {
                name: "statsforecast",
                groups: .[1]
              },
              {
                name: "mlforecast",
                groups: .[2]
              },
              {
                name: "neuralforecast",
                groups: .[3]
              },
              {
                name: "hierarchicalforecast",
                groups: .[4]
              }
            ]
          }
          | .navigations |= map(
            .name as $prefix 
            | .groups |= walk(
              if type == "array" 
                then map(
                  if type == "string"
                    then $prefix + "/" + .
                    else .
                  end
                )
                else . 
              end
            )
          )
          | .config.navigation = (
            [.navigations[].groups]
            | add
          ) 
          | .config' mint.json a/navigation.json b/navigation.json c/navigation.json d/navigation.json

      - name: Clone statsforecast
        uses: actions/checkout@v3
        with:
          path: statsforecast
          repository: 'Nixtla/statsforecast'
          ref: 'gh-pages'
      - name: Clone mlforecast
        uses: actions/checkout@v3
        with:
          path: mlforecast
          repository: 'Nixtla/mlforecast'
          ref: 'gh-pages'
      - name: Clone neuralforecast
        uses: actions/checkout@v3
        with:
          path: neuralforecast
          repository: 'Nixtla/neuralforecast'
          ref: 'gh-pages'
      - name: Clone hierarchicalforecast
        uses: actions/checkout@v3
        with:
          path: hierarchicalforecast
          repository: 'Nixtla/hierarchicalforecast'
          ref: 'gh-pages'

      - name: Remove .git folders
        run: rm -rf */.git 
      - name: Push files
        run: |
          git config user.name "Mintie Bot"
          git config user.email "aws@mintlify.com"
          git add .
          git commit -m "update"
          git push origin main
