name: Test jq

on: workflow_dispatch

jobs:
  test-jq:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test jq
        run: |
          jq -s '{
            config: .[0],
            navigations: [
              {
                name: "statsforecast",
                groups: .[1]
              },
              {
                name: "mlforecast",
                groups: .[2]
              },
              {
                name: "neuralforecast",
                groups: .[3]
              },
              {
                name: "hierarchicalforecast",
                groups: .[4]
              }
            ]
          }
          | .navigations |= map(
            .name as $prefix 
            | .groups |= walk(
              if type == "array" 
                then map(
                  if type == "string"
                    then $prefix + "/" + .
                    else .
                  end
                )
                else . 
              end
            )
          )
          | .config.navigation = (
            [.navigations[].groups]
            | add
          ) 
          | .config' mint.json a/navigation.json b/navigation.json c/navigation.json d/navigation.json
