name: Update

on:
  workflow_dispatch:
  repository_dispatch:
    types: [update]

concurrency:
  group: update
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PUSH_TOKEN }}
      - name: Clean repo
        run: rm -rf statsforecast mlforecast neuralforecast hierarchicalforecast

      - name: Clone nixtla
        uses: actions/checkout@v3
        with:
          path: nixtla
          repository: 'Nixtla/nixtla'
          ref: 'docs'
      - name: Clone statsforecast
        uses: actions/checkout@v3
        with:
          path: statsforecast
          repository: 'Nixtla/statsforecast'
          ref: 'docs'
      - name: Clone mlforecast
        uses: actions/checkout@v3
        with:
          path: mlforecast
          repository: 'Nixtla/mlforecast'
          ref: 'docs'
      - name: Clone neuralforecast
        uses: actions/checkout@v3
        with:
          path: neuralforecast
          repository: 'Nixtla/neuralforecast'
          ref: 'docs'
      - name: Clone hierarchicalforecast
        uses: actions/checkout@v3
        with:
          path: hierarchicalforecast
          repository: 'Nixtla/hierarchicalforecast'
          ref: 'docs'
      - name: Clone utilsforecast
        uses: actions/checkout@v3
        with:
          path: statsforecast
          repository: 'Nixtla/utilsforecast'
          ref: 'docs'
      - name: Clone datasetsforecast
        uses: actions/checkout@v3
        with:
          path: statsforecast
          repository: 'Nixtla/datasetsforecast'
          ref: 'docs'
      - name: Clone coreforecast
        uses: actions/checkout@v3
        with:
          path: statsforecast
          repository: 'Nixtla/coreforecast'
          ref: 'docs'
      - name: Remove .git folders
        run: rm -rf */.git

      - name: Compile mint.json
        run: |
          jq -s '{
            config: .[0],
            navigations: [
              {
                name: "nixtla",
                groups: .[1]
              },
              {
                name: "statsforecast",
                groups: .[2]
              },
              {
                name: "mlforecast",
                groups: .[3]
              },
              {
                name: "neuralforecast",
                groups: .[4]
              },
              {
                name: "hierarchicalforecast",
                groups: .[5]
              },
              {
                name: "utilsforecast",
                groups: .[6]
              },
              {
                name: "datasetsforecast",
                groups: .[7]
              },
              {
                name: "coreforecast",
                groups: .[8]
              }
            ]
          }
          | .navigations |= map(
            .name as $prefix 
            | .groups |= walk(
              if type == "array" 
                then map(
                  if type == "string"
                    then $prefix + "/" + .
                    else .
                  end
                )
                else . 
              end
            )
          )
          | .config.navigation = (
            [.navigations[].groups]
            | add
          ) 
          | .config' mint.json a/navigation.json b/navigation.json c/navigation.json d/navigation.json > mint-temp.json
          mv mint-temp.json mint.json

      # only runs when changed files are detected
      - name: Push changes
        run: |
          git config user.name "Mintie Bot"
          git config user.email "aws@mintlify.com"
          git add .
          if git diff-index --quiet --cached HEAD -- ; then
            echo 'No changes detected, skipping...'
          else
            git commit -m "update"
            git push origin main
          fi
