name: Update

on:
  workflow_dispatch:
  repository_dispatch:
    types: [update]

concurrency:
  group: update
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PUSH_TOKEN }}
      - name: Clean repo
        run: rm -rf statsforecast mlforecast neuralforecast hierarchicalforecast

      - name: Clone statsforecast
        uses: actions/checkout@v3
        with:
          path: statsforecast
          repository: 'Nixtla/statsforecast'
          ref: 'gh-pages'
      - name: Clone mlforecast
        uses: actions/checkout@v3
        with:
          path: mlforecast
          repository: 'Nixtla/mlforecast'
          ref: 'gh-pages'
      - name: Clone neuralforecast
        uses: actions/checkout@v3
        with:
          path: neuralforecast
          repository: 'Nixtla/neuralforecast'
          ref: 'gh-pages'
      - name: Clone hierarchicalforecast
        uses: actions/checkout@v3
        with:
          path: hierarchicalforecast
          repository: 'Nixtla/hierarchicalforecast'
          ref: 'gh-pages'

      - name: Remove .git folders
        run: rm -rf */.git

      - name: Check for modified files
        run: '! git diff-files --quiet'
        shell: bash
        continue-on-error: true
      # only runs when changed files are detected
      - name: Push files
        if: success()
        run: |
          git config user.name "Mintie Bot"
          git config user.email "aws@mintlify.com"
          git add .
          git commit -m "update"
          git push origin main
