name: Update

on:
  workflow_dispatch:
  repository_dispatch:
    types: [update]

concurrency:
  group: update
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure git
        run: |
          git config --global user.name "Mintie Bot"
          git config --global user.email "aws@mintlify.com"
      - name: Clean repo
        run: rm -rf statsforecast
      - name: Clone first repo
        uses: actions/checkout@v3
        with:
          path: statsforecast
          repository: 'Nixtla/statsforecast'
          ref: 'gh-pages'
      - name: Remove .git folder
        run: rm -rf statsforecast/.git
      - name: Check updated files
        run: git status
      - name: Commit files
        run: |
          git add statsforecast
          git commit -m "update"
      - name: Push files
        run: git push origin main

